In [13]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


In [2]:
df=pd.read_csv('Final_data.csv',encoding="cp1252")
df

Unnamed: 0        Date  Piligrims  Tonsures  Hundi  Speciality  \
0             0  2022-01-01      36560     14084   2.15           5   
1             1  2022-02-01      38894     12270   3.93           4   
2             2  2022-03-01      31776     16046   2.69           5   
3             3  2022-04-01      31523     14692   2.45           4   
4             4  2022-05-01      32044     17558   2.61           5   
..          ...         ...        ...       ...    ...         ...   
360         360  27/12/2022      70496     25500   5.88           0   
361         361  28/12/2022      71299     28288   3.26           0   
362         362  29/12/2022      67156     24752   4.92           0   
363         363  30/12/2022      63253     24490   5.16           0   
364         364  31/12/2022      71069     34741   4.98           0   

     Temperature  Condition  ttd online darshan tickets  Tirupati  ...  \
0             77       1275                           0        43  ...   
1             79        972                           6        41  ...   
2             79        972                          10        40  ...   
3             79        972                           0        45  ...   
4             79        972                           8        32  ...   
..           ...        ...                         ...       ...  ...   
360           79       1275                          34        80  ...   
361           82        972                          37        74  ...   
362           82        862                           0        75  ...   
363           82        972                          22        77  ...   
364           82        862                          45        55  ...   

     ksrtc tirupati package  srinivasam complex  tirumala darshan tickets  \
0                         0                   0                         0   
1                         0                   0                         0   
2                         0                   0                         0   
3                        53                   0                         0   
4                         0                   0                        18   
..                      ...                 ...                       ...   
360                       2                   0                        38   
361                       0                  17                        39   
362                       0                   0                        20   
363                       0                  16                        20   
364                       5                  32                        35   

     tirumala darshan  tirupati balaji.ap.gov.in  \
0                   9                          0   
1                   9                          0   
2                   5                          7   
3                  16                          0   
4                  10                          7   
..                ...                        ...   
360                46                         13   
361                40                         24   
362                38                         18   
363                36                         16   
364                53                         33   

     tirupati darshan 500 rupees ticket  \
0                                     0   
1                                     0   
2                                     0   
3                                     0   
4                                     0   
..                                  ...   
360                                   0   
361                                   0   
362                                   0   
363                                   0   
364                                  32   

     ttd free darshan online booking availability.1  Week_day  Review  \
0                                                 0         1      -1   
1                                                 

In [3]:
#!pip install xgboost

In [4]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Unnamed: 0                                      365 non-null    int64  
 1   Date                                            365 non-null    object 
 2   Piligrims                                       365 non-null    int64  
 3   Tonsures                                        365 non-null    int64  
 4   Hundi                                           365 non-null    float64
 5   Speciality                                      365 non-null    int64  
 6   Temperature                                     365 non-null    int64  
 7   Condition                                       365 non-null    int64  
 8   ttd online darshan tickets                      365 non-null    int64  
 9   Tirupati                                   

In [5]:
df.describe()

Unnamed: 0     Piligrims      Tonsures       Hundi  Speciality  \
count  365.000000    365.000000    365.000000  365.000000  365.000000   
mean   182.000000  64976.172603  29867.024658    3.995589    2.643836   
std    105.510663  15579.602735   8313.897563    0.877867    2.661126   
min      0.000000  22423.000000   9645.000000    1.590000    0.000000   
25%     91.000000  61654.000000  26421.000000    3.610000    0.000000   
50%    182.000000  68467.000000  30884.000000    4.190000    2.000000   
75%    273.000000  74412.000000  34774.000000    4.530000    5.000000   
max    364.000000  93400.000000  52969.000000    6.310000    7.000000   

       Temperature    Condition  ttd online darshan tickets    Tirupati  \
count   365.000000   365.000000                  365.000000  365.000000   
mean     87.098630  1295.073973                   10.534247   57.446575   
std       6.436172   456.526124                   13.227180   11.678407   
min      66.000000   432.000000                    0.000000   25.000000   
25%      82.000000   972.000000                    0.000000   52.000000   
50%      86.000000  1291.000000                    8.000000   59.000000   
75%      91.000000  1324.000000                   14.000000   64.000000   
max     102.000000  2802.000000                  100.000000  100.000000   

         Tirumala  ...  ksrtc tirupati package  srinivasam complex  \
count  365.000000  ...              365.000000          365.000000   
mean    35.523288  ...                9.005479           10.347945   
std     13.230112  ...               18.734407           15.513448   
min     13.000000  ...                0.000000            0.000000   
25%     27.000000  ...                0.000000            0.000000   
50%     32.000000  ...                0.000000            0.000000   
75%     43.000000  ...                2.000000           18.000000   
max    100.000000  ...              100.000000          100.000000   

       tirumala darshan tickets  tirumala darshan  tirupati balaji.ap.gov.in  \
count                365.000000        365.000000                 365.000000   
mean                  17.482192         21.317808                  12.117808   
std                   14.453329         12.226697                  16.961490   
min                    0.000000          2.000000                   0.000000   
25%                    9.000000         14.000000                   0.000000   
50%                   15.000000         18.000000                   7.000000   
75%                   23.000000         26.000000                  17.000000   
max                  100.000000        100.000000                 100.000000   

       tirupati darshan 500 rupees ticket  \
count                          365.000000   
mean                            10.682192   
std                             20.689033   
min                              0.000000   
25%                              0.000000   
50%                              0.000000   
75%                             20.000000   
max                            100.000000   

       ttd free darshan online booking availability.1    Week_day      Review  \
count                                      365.000000  365.000000  365.000000   
mean                                        10.520548    0.287671    0.210959   
std                                         15.779829    0.453298    0.520872   
min                                          0.000000    0.000000   -1.000000   
25%                                          0.000000    0.000000    0.000000   
50%                                          0.000000    0.000000    0.000000   
75%                                         16.000000    1.000000    1.000000   
max                                        100.000000    1.000000    1.000000   

          Timestamp  
count  3.650000e+02  
mean   1.656700e+09  
std    9.116121e+06  
min    1.640975e+09  
25%    1.648838e+09  
50%    1.656700e+09  
75%    1.664563e+09  
max    1.

In [6]:
#removing the uwanted attributes
df=df.drop('Unnamed: 0',axis=1)

In [7]:
df.columns


Index(['Date', 'Piligrims', 'Tonsures', 'Hundi', 'Speciality', 'Temperature',
       'Condition', 'ttd online darshan tickets', 'Tirupati', 'Tirumala',
       'VIP darshan', 'How to reach Tirupati', 'ttd sarva darshan tickets',
       'ttd free darshan online booking availability',
       'apsrtc tirumala darshan tickets', 'apsrtc ttd 300 tickets',
       'ksrtc tirupati package', 'srinivasam complex',
       'tirumala darshan tickets', 'tirumala darshan',
       'tirupati balaji.ap.gov.in', 'tirupati darshan 500 rupees ticket',
       'ttd free darshan online booking availability.1', 'Week_day', 'Review',
       'Timestamp'],
      dtype='object')

In [8]:
x=np.array(df[[
       'Temperature', 'Condition', 'ttd online darshan tickets', 'Tirupati',
       'Tirumala', 'VIP darshan', 'Week_day', 
       'Timestamp']])
y=np.array(df['Piligrims'])

In [9]:

l=[]
#
#for i in range(1000): 
#    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.18,random_state=i)
#    import lightgbm as lgb
#    model=lgb.LGBMRegressor()
#    model.fit(x_train,y_train)
#    y_pre#d=model.predict(x_test)
#    accuracy1=model.score(x_train,y_train)
#    #print("The  training accuracy is ",ac#curacy1)
#    accuracy2=model.score(x_test,y_test)
#    #print("The  testing accuracy is ",accuracy2)
#    #print(i,'\n')
#    l.append(accuracy2)
#b=max(l)
#print(b)#

In [10]:
#df.corr()

In [11]:
#for j in range(1000):
#    if(l[j]==b):
#        print(j)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.27,random_state=3)
import lightgbm as lgb
model=lgb.LGBMRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy1=model.score(x_train,y_train)
print("The  training accuracy is ",accuracy1)
accuracy2=model.score(x_test,y_test)
print("The  testing accuracy is ",accuracy2)




[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000206 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 273
[LightGBM] [Info] Number of data points in the train set: 266, number of used features: 8
[LightGBM] [Info] Start training from score 65097.988722
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive ga

In [15]:
y_train

array([73358, 27446, 73387, 59086, 80815, 81287, 58747, 57904, 83422,
       74288, 25549, 71069, 73371, 82722, 72195, 63759, 70727, 61620,
       75324, 72265, 89013, 71689, 62055, 75759, 64107, 55532, 64336,
       82392, 63214, 36333, 32044, 65756, 75400, 81318, 72851, 66745,
       65725, 78479, 62856, 84211, 48928, 61731, 68467, 76425, 71289,
       84982, 31523, 90165, 61654, 70408, 61052, 34187, 68469, 33356,
       69012, 80312, 83739, 72466, 70373, 69115, 22423, 79525, 83223,
       31794, 51308, 75759, 75407, 70848, 70674, 45481, 67858, 68095,
       70007, 67276, 64292, 66020, 67950, 27896, 93400, 74823, 57581,
       68539, 61654, 66072, 61304, 62001, 54273, 69628, 28410, 61982,
       67468, 69278, 71119, 63145, 69383, 63084, 70560, 46118, 54396,
       77273, 80294, 74094, 79103, 71069, 81034, 65840, 77541, 32894,
       67750, 84885, 92328, 37304, 67525, 70134, 33971, 25524, 63332,
       73375, 56958, 39619, 71167, 59528, 87698, 61224, 60946, 64438,
       65158, 70496,

In [16]:
y_pred

array([68282.47875294, 76399.00776844, 78701.80786346, 37637.94647274,
       76163.77073996, 70962.35207367, 70391.26655881, 76354.69065659,
       67202.01511491, 73774.82403948, 69318.53125952, 32115.45926432,
       68337.41614698, 56963.56334684, 71667.13715695, 65771.70766953,
       48962.41464578, 30420.98590422, 69359.96545625, 80949.28923873,
       29843.902991  , 62261.35908639, 71370.13923557, 68530.15017818,
       72585.6275279 , 67002.22842891, 80226.98274426, 69644.59353491,
       29465.19822001, 34051.70493018, 58168.54671216, 68308.4164008 ,
       75635.05607528, 73251.33174483, 76419.29896962, 66931.91608073,
       57935.89909109, 67809.3247166 , 64509.0265898 , 76377.23494221,
       39932.51189028, 70402.01150742, 69915.72240621, 76032.03574308,
       62527.572311  , 77494.29793686, 64779.81997745, 59343.54584186,
       45330.84722125, 68231.02474875, 65778.20414946, 83816.83897881,
       59639.096406  , 67964.50599288, 85892.98317574, 64214.67095979,
      

In [17]:
y_test

array([88748, 73831, 74297, 28745, 81720, 70019, 71914, 71069, 78299,
       71196, 75382, 35642, 75175, 65704, 65898, 77277, 50511, 29496,
       72873, 79836, 35516, 70263, 74304, 63754, 74231, 63670, 86188,
       74503, 32894, 35333, 61654, 64157, 80565, 74389, 73439, 61863,
       58561, 71069, 67681, 76746, 24888, 83880, 69897, 71528, 72567,
       88924, 74817, 64368, 56559, 69154, 60157, 79833, 63042, 74354,
       87478, 65466, 73016, 81535, 65418, 73323, 62725, 69211, 37216,
       69814, 74830, 23744, 76324, 60861, 74497, 69603, 72067, 27223,
       69640, 57104, 75876, 84794, 72243, 78188, 53163, 41390, 30172,
       60946, 62141, 71299, 69711, 65763, 29652, 66577, 34375, 39335,
       39691, 71437, 84878, 64425, 26401, 76418, 71158, 78602, 68128],
      dtype=int64)

In [18]:
accuracy1=model.score(x_train,y_train)
print("The  training accuracy is ",accuracy1)
accuracy2=model.score(x_test,y_test)
print("The  testing accuracy is ",accuracy2)

The  training accuracy is  0.919013920772436
The  testing accuracy is  0.8601541379405162


In [19]:
y_test

array([88748, 73831, 74297, 28745, 81720, 70019, 71914, 71069, 78299,
       71196, 75382, 35642, 75175, 65704, 65898, 77277, 50511, 29496,
       72873, 79836, 35516, 70263, 74304, 63754, 74231, 63670, 86188,
       74503, 32894, 35333, 61654, 64157, 80565, 74389, 73439, 61863,
       58561, 71069, 67681, 76746, 24888, 83880, 69897, 71528, 72567,
       88924, 74817, 64368, 56559, 69154, 60157, 79833, 63042, 74354,
       87478, 65466, 73016, 81535, 65418, 73323, 62725, 69211, 37216,
       69814, 74830, 23744, 76324, 60861, 74497, 69603, 72067, 27223,
       69640, 57104, 75876, 84794, 72243, 78188, 53163, 41390, 30172,
       60946, 62141, 71299, 69711, 65763, 29652, 66577, 34375, 39335,
       39691, 71437, 84878, 64425, 26401, 76418, 71158, 78602, 68128],
      dtype=int64)

In [20]:
y_train

array([73358, 27446, 73387, 59086, 80815, 81287, 58747, 57904, 83422,
       74288, 25549, 71069, 73371, 82722, 72195, 63759, 70727, 61620,
       75324, 72265, 89013, 71689, 62055, 75759, 64107, 55532, 64336,
       82392, 63214, 36333, 32044, 65756, 75400, 81318, 72851, 66745,
       65725, 78479, 62856, 84211, 48928, 61731, 68467, 76425, 71289,
       84982, 31523, 90165, 61654, 70408, 61052, 34187, 68469, 33356,
       69012, 80312, 83739, 72466, 70373, 69115, 22423, 79525, 83223,
       31794, 51308, 75759, 75407, 70848, 70674, 45481, 67858, 68095,
       70007, 67276, 64292, 66020, 67950, 27896, 93400, 74823, 57581,
       68539, 61654, 66072, 61304, 62001, 54273, 69628, 28410, 61982,
       67468, 69278, 71119, 63145, 69383, 63084, 70560, 46118, 54396,
       77273, 80294, 74094, 79103, 71069, 81034, 65840, 77541, 32894,
       67750, 84885, 92328, 37304, 67525, 70134, 33971, 25524, 63332,
       73375, 56958, 39619, 71167, 59528, 87698, 61224, 60946, 64438,
       65158, 70496,

In [21]:
from sklearn.model_selection import KFold

In [22]:
#params = {
#    'objective': 'mse',
#    'metric': 'RMSE',
#    'boosting_type': 'gbdt',
#    'num_leaves': 31,
#    'learning_rate': 0.05,
#    'feature_fraction': 0.9
#}

In [23]:
#kf = KFold(n_splits=15, shuffle=True, random_state=42)

In [24]:
#cv_results = lgb.cv(
#    params,
#    lgb.Dataset(x, y),
#    num_boost_round=1000,
#    folds=kf.split(x),
#    early_stopping_rounds=100,
#    verbose_eval=False
#)
#
#print('CV results:', cv_results)

In [25]:
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
import numpy as np
kf = KFold(n_splits=6, shuffle=True, random_state=815)  
model2=lgb.LGBMRegressor()
accuracies = []  
for train_idx, test_idx in kf.split(x):
    x_train1, y_train1 = x[train_idx], y[train_idx]  # Get the training data for this fold
    x_test1, y_test1 = x[test_idx], y[test_idx]  # Get the test data for this fold

    # Train your model on the training data
    model2.fit(x_train1, y_train1)

    # Make predictions on the test data and calculate accuracy
    y_pred1 = model2.predict(x_test1)
    accuracy21=model2.score(x_test1,y_test1)
    print("The  testing accuracy is ",accuracy21)
    accuracies.append(accuracy21)

mean_accuracy = np.mean(accuracies) # Calculate the mean accuracy across all folds
print("mean_accuracy is",mean_accuracy)


[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000245 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 299
[LightGBM] [Info] Number of data points in the train set: 304, number of used features: 8
[LightGBM] [Info] Start training from score 65255.345395
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive ga

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

In [26]:
print("mean_accuracy is",mean_accuracy)
#!pip install tensorflow

mean_accuracy is 0.7613404660289448


In [ ]:
#import tensorflow as tf

In [ ]:
#import numpy as np
#import tensorflow as tf
#from tensorflow.keras.models import Sequential
#from tensorflow.keras.layers import LSTM, Dense